// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/todo.proto

/*
Package todo is a generated protocol buffer package.

It is generated from these files:
	proto/todo.proto

It has these top-level messages:
	Todo
	CreateTodoRequest
	CreateTodoResponse
	ReadTodoRequest
	ReadTodoResponse
	UpdateTodoRequest
	UpdateTodoResponse
	DeleteTodoRequest
	DeleteTodoResponse
	ListTodosRequest
	ListTodosResponse
*/
package todo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Todo struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Completed bool   `protobuf:"varint,3,opt,name=completed" json:"completed,omitempty"`
}

func (m *Todo) Reset()                    { *m = Todo{} }
func (m *Todo) String() string            { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()               {}
func (*Todo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Todo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Todo) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type CreateTodoRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Completed bool   `protobuf:"varint,2,opt,name=completed" json:"completed,omitempty"`
}

func (m *CreateTodoRequest) Reset()                    { *m = CreateTodoRequest{} }
func (m *CreateTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTodoRequest) ProtoMessage()               {}
func (*CreateTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateTodoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTodoRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type CreateTodoResponse struct {
	Todo *Todo `protobuf:"bytes,1,opt,name=todo" json:"todo,omitempty"`
}

func (m *CreateTodoResponse) Reset()                    { *m = CreateTodoResponse{} }
func (m *CreateTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTodoResponse) ProtoMessage()               {}
func (*CreateTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type ReadTodoRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadTodoRequest) Reset()                    { *m = ReadTodoRequest{} }
func (m *ReadTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadTodoRequest) ProtoMessage()               {}
func (*ReadTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadTodoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadTodoResponse struct {
	Todo *Todo `protobuf:"bytes,1,opt,name=todo" json:"todo,omitempty"`
}

func (m *ReadTodoResponse) Reset()                    { *m = ReadTodoResponse{} }
func (m *ReadTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadTodoResponse) ProtoMessage()               {}
func (*ReadTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type UpdateTodoRequest struct {
	Id        uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Completed bool   `protobuf:"varint,3,opt,name=completed" json:"completed,omitempty"`
}

func (m *UpdateTodoRequest) Reset()                    { *m = UpdateTodoRequest{} }
func (m *UpdateTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTodoRequest) ProtoMessage()               {}
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateTodoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTodoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateTodoRequest) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type UpdateTodoResponse struct {
	Todo *Todo `protobuf:"bytes,1,opt,name=todo" json:"todo,omitempty"`
}

func (m *UpdateTodoResponse) Reset()                    { *m = UpdateTodoResponse{} }
func (m *UpdateTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateTodoResponse) ProtoMessage()               {}
func (*UpdateTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateTodoResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type DeleteTodoRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteTodoRequest) Reset()                    { *m = DeleteTodoRequest{} }
func (m *DeleteTodoRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTodoRequest) ProtoMessage()               {}
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteTodoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTodoResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteTodoResponse) Reset()                    { *m = DeleteTodoResponse{} }
func (m *DeleteTodoResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteTodoResponse) ProtoMessage()               {}
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteTodoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListTodosRequest struct {
}

func (m *ListTodosRequest) Reset()                    { *m = ListTodosRequest{} }
func (m *ListTodosRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTodosRequest) ProtoMessage()               {}
func (*ListTodosRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ListTodosResponse struct {
	Todos []*Todo `protobuf:"bytes,1,rep,name=todos" json:"todos,omitempty"`
}

func (m *ListTodosResponse) Reset()                    { *m = ListTodosResponse{} }
func (m *ListTodosResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTodosResponse) ProtoMessage()               {}
func (*ListTodosResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ListTodosResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

func init() {
	proto.RegisterType((*Todo)(nil), "todo.Todo")
	proto.RegisterType((*CreateTodoRequest)(nil), "todo.CreateTodoRequest")
	proto.RegisterType((*CreateTodoResponse)(nil), "todo.CreateTodoResponse")
	proto.RegisterType((*ReadTodoRequest)(nil), "todo.ReadTodoRequest")
	proto.RegisterType((*ReadTodoResponse)(nil), "todo.ReadTodoResponse")
	proto.RegisterType((*UpdateTodoRequest)(nil), "todo.UpdateTodoRequest")
	proto.RegisterType((*UpdateTodoResponse)(nil), "todo.UpdateTodoResponse")
	proto.RegisterType((*DeleteTodoRequest)(nil), "todo.DeleteTodoRequest")
	proto.RegisterType((*DeleteTodoResponse)(nil), "todo.DeleteTodoResponse")
	proto.RegisterType((*ListTodosRequest)(nil), "todo.ListTodosRequest")
	proto.RegisterType((*ListTodosResponse)(nil), "todo.ListTodosResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoService service

type TodoServiceClient interface {
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error)
	ReadTodo(ctx context.Context, in *ReadTodoRequest, opts ...grpc.CallOption) (*ReadTodoResponse, error)
	UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoResponse, error)
	DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error)
	ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (*ListTodosResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error) {
	out := new(CreateTodoResponse)
	err := grpc.Invoke(ctx, "/todo.TodoService/CreateTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ReadTodo(ctx context.Context, in *ReadTodoRequest, opts ...grpc.CallOption) (*ReadTodoResponse, error) {
	out := new(ReadTodoResponse)
	err := grpc.Invoke(ctx, "/todo.TodoService/ReadTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*UpdateTodoResponse, error) {
	out := new(UpdateTodoResponse)
	err := grpc.Invoke(ctx, "/todo.TodoService/UpdateTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error) {
	out := new(DeleteTodoResponse)
	err := grpc.Invoke(ctx, "/todo.TodoService/DeleteTodo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (*ListTodosResponse, error) {
	out := new(ListTodosResponse)
	err := grpc.Invoke(ctx, "/todo.TodoService/ListTodos", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TodoService service

type TodoServiceServer interface {
	CreateTodo(context.Context, *CreateTodoRequest) (*CreateTodoResponse, error)
	ReadTodo(context.Context, *ReadTodoRequest) (*ReadTodoResponse, error)
	UpdateTodo(context.Context, *UpdateTodoRequest) (*UpdateTodoResponse, error)
	DeleteTodo(context.Context, *DeleteTodoRequest) (*DeleteTodoResponse, error)
	ListTodos(context.Context, *ListTodosRequest) (*ListTodosResponse, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ReadTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ReadTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/ReadTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ReadTodo(ctx, req.(*ReadTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).UpdateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/UpdateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).UpdateTodo(ctx, req.(*UpdateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/DeleteTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DeleteTodo(ctx, req.(*DeleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ListTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ListTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.TodoService/ListTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ListTodos(ctx, req.(*ListTodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _TodoService_CreateTodo_Handler,
		},
		{
			MethodName: "ReadTodo",
			Handler:    _TodoService_ReadTodo_Handler,
		},
		{
			MethodName: "UpdateTodo",
			Handler:    _TodoService_UpdateTodo_Handler,
		},
		{
			MethodName: "DeleteTodo",
			Handler:    _TodoService_DeleteTodo_Handler,
		},
		{
			MethodName: "ListTodos",
			Handler:    _TodoService_ListTodos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/todo.proto",
}

func init() { proto.RegisterFile("proto/todo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0x9a, 0xb7, 0x6f, 0xfb, 0x14, 0xb4, 0x19, 0xd0, 0x86, 0x22, 0x12, 0xe3, 0xa5,
	0xa7, 0x0a, 0xb5, 0x1e, 0x04, 0xa1, 0xe0, 0x1f, 0xf0, 0xe0, 0x29, 0xda, 0x8b, 0xb7, 0x9a, 0xcc,
	0x21, 0x60, 0xbb, 0xb1, 0x9b, 0xfa, 0x1d, 0xfd, 0x56, 0xb2, 0x9b, 0xa4, 0x09, 0x9b, 0x2a, 0x05,
	0x6f, 0xbb, 0xb3, 0x33, 0xbf, 0x99, 0x79, 0x9e, 0x04, 0xfd, 0x74, 0x2d, 0x32, 0x71, 0x91, 0x89,
	0x58, 0x8c, 0xf5, 0x91, 0x1c, 0x75, 0x0e, 0x1e, 0xe1, 0xbc, 0x88, 0x58, 0xd0, 0x01, 0xec, 0x24,
	0xf6, 0x2c, 0xdf, 0x1a, 0x39, 0xa1, 0x9d, 0xc4, 0x44, 0x70, 0x56, 0x8b, 0x25, 0x7b, 0xb6, 0x6f,
	0x8d, 0xba, 0xa1, 0x3e, 0xd3, 0x09, 0xba, 0x91, 0x58, 0xa6, 0xef, 0x9c, 0x71, 0xec, 0xb5, 0x7c,
	0x6b, 0xd4, 0x09, 0xab, 0x40, 0xf0, 0x00, 0xf7, 0x6e, 0xcd, 0x8b, 0x8c, 0x15, 0x2f, 0xe4, 0x8f,
	0x0d, 0xcb, 0x6c, 0x8b, 0xb1, 0x7e, 0xc2, 0xd8, 0x26, 0x66, 0x0a, 0xaa, 0x63, 0x64, 0x2a, 0x56,
	0x92, 0xe9, 0x14, 0x7a, 0x5c, 0xcd, 0xe9, 0x4d, 0x30, 0xd6, 0x7b, 0xe8, 0x8c, 0x7c, 0x8d, 0x33,
	0x1c, 0x86, 0xbc, 0x88, 0xeb, 0xad, 0x8d, 0x8d, 0x82, 0x09, 0xfa, 0x55, 0xca, 0x9e, 0xd8, 0x39,
	0xdc, 0x79, 0x1a, 0x1b, 0x3b, 0xfd, 0x5d, 0xaa, 0x29, 0xa8, 0x8e, 0xdd, 0x73, 0x98, 0x73, 0xb8,
	0xf7, 0xac, 0x00, 0xbf, 0x6d, 0x39, 0x06, 0xd5, 0x93, 0x0a, 0xb4, 0x87, 0xff, 0x72, 0x13, 0x45,
	0x2c, 0xa5, 0x4e, 0xed, 0x84, 0xe5, 0x35, 0x20, 0xf4, 0x9f, 0x12, 0x99, 0xa9, 0x6c, 0x59, 0x30,
	0x83, 0x2b, 0xb8, 0xb5, 0x58, 0x81, 0xf0, 0xf1, 0x4f, 0x4d, 0xa1, 0x00, 0x2d, 0x63, 0xbc, 0xfc,
	0x61, 0xf2, 0x65, 0xa3, 0xa7, 0xee, 0xcf, 0xbc, 0xfe, 0x4c, 0x22, 0xa6, 0x19, 0x50, 0x39, 0x49,
	0x83, 0xbc, 0xa0, 0xf1, 0x89, 0x0c, 0xbd, 0xe6, 0x43, 0xd1, 0xf2, 0x1a, 0x9d, 0xd2, 0x31, 0x3a,
	0xca, 0xb3, 0x0c, 0x93, 0x87, 0xc7, 0x66, 0xb8, 0x28, 0x9d, 0x01, 0x95, 0xc2, 0x65, 0xef, 0x86,
	0x95, 0x65, 0xef, 0x1d, 0x66, 0xcc, 0x80, 0x4a, 0xc7, 0x12, 0xd0, 0x90, 0xbf, 0x04, 0xec, 0x90,
	0xfc, 0x06, 0xdd, 0xad, 0x88, 0x54, 0x8c, 0x69, 0x2a, 0x3d, 0x1c, 0x34, 0xe2, 0x79, 0xf5, 0x6d,
	0xfb, 0x55, 0x7b, 0xfe, 0xd6, 0xd6, 0xff, 0xea, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0x1b, 0xec, 0xdd, 0xbf, 0x03, 0x00, 0x00,
}
